#!/bin/bash

echo " * Configuring DNS client..."
echo "
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver $PRIMARY_DNS
nameserver $SECUNDARY_DNS
#search localdomain

" > /etc/resolv.conf